### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by BANanaD3V** [jwenjian/visitor-badge#17]
Can you please make styles? Like, if I will use https://visitor-badge.glitch.me/badge?page_id=BANanaD3V.BANanaD3V&style=for-the-badge, it will be like the shield.io with this style. I think it's not hard, I think you are using shields.io. And if I will refresh page, the counter will encrease. Can you make one user = one count

**Comment by jwenjian** [comment]
Hi, actually I am not using shields.io, I am using a python library [pybadges](https://github.com/google/pybadges).

And one user = one count is not possible for this project since I cannot distinguish the unique user.

For the styles, I see the pybadges support some colors and logos, may be there will be more parameters to customize the color, but I cannot give you a time though.

**Comment by jwenjian** [comment]
new release is out
