### ISSUE TITLE
Hosted On Deta 24/7 (visitor-badge.deta.dev)

### ISSUE THREAD

**Issue by AmreshSinha** [jwenjian/visitor-badge#18]
I have hosted the visitor-badge on deta.dev as it goes down on glitch on many requests.
It's totally free and your app doesn't sleep or gives error on many requests like it does on glitch.me.

Here's the link: https://visitor-badge.deta.dev/

![Visitor-Badge](https://visitor-badge.deta.dev/badge?page_id=jwenjian.visitor-badge)

![Visitor-Badge](https://visitor-badge.deta.dev/badge?page_id=jwenjian.visitor-badge&left_color=red&right_color=green) (left_color=red, right_color=green)

You can add this in the README so that others can use this too :)

**Comment by jwenjian** [comment]
Thanks， well noted ， will update the README then



发自我的iPhone


------------------ Original ------------------
From: Amresh Prasad Sinha ***@***.***&gt;
Date: Thu,Sep 16,2021 10:35 PM
To: jwenjian/visitor-badge ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [jwenjian/visitor-badge] Hosted On Deta 24/7 (visitor-badge.deta.dev) (#18)





 
I have hosted the visitor-badge on deta.dev as it goes down on glitch on many requests.
 It's totally free and your app doesn't sleep or gives error on many requests like it does on glitch.me.
 
Here's the link: https://visitor-badge.deta.dev/
 

 
 (left_color=red, right_color=green)
 
You can add this in the README so that others can use this too :)
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jwenjian** [comment]
Updated
