### ISSUE TITLE
Potential bug in visitor count?

### ISSUE THREAD

**Issue by irmakerdem** [jwenjian/visitor-badge#28]
Hi! Thank you so much for allowing public access to create a visitor counter for GitHub profile. I ran into an issue and was wondering if you could explain. I copied and pasted the code for my GitHub profile's README but while editing I realized that _ANY_ visit to the readme counts (including from me!). Is it true that the visitor count is not unique to visitors from same IP address? Currently every time I toggle between the "edit" and "preview" tabs of the README.md, I am seeing the number increase (without even committing). Please provide clarity if you can! Thank you

**Comment by jwenjian** [comment]
Hi, yes, you are right, the number increase when every page loaded, it does not count on unique visitor based on IP address.

This is because all the image is proxied by Github camo server, so visitor badge server cannot access your original IP address.

So it's more like a limitation instead of a bug from my point of view.

**Comment by ledges** [comment]
> Hi, yes, you are right, the number increase when every page loaded, it does not count on unique visitor based on IP address.
> 
> This is because all the image is proxied by Github camo server, so visitor badge server cannot access your original IP address.
> 
> So it's more like a limitation instead of a bug from my point of view.

There is a workaround for this: make your program only add views if the request header matches the camo server's.
