### ISSUE TITLE
Badge shows user many times

### ISSUE THREAD

**Issue by dart-coder** [jwenjian/visitor-badge#8]
It means that I can refresh the page and it will count me to visitors again. Even if I'm a creator of this repository.

**Comment by jwenjian** [comment]
@dart-coder Hi, yes you're right, actually, it's not a VISITOR badge, it's a PAGE VIEW COUNT badge :-)

The principle is simple, the count will increment by 1 if the page is loaded.

Server does not(can not) distinguish which one is browsing this page, even you are the creator of the repository, so no tracking(like google analytics)

Hope this make things more clear.

**Comment by Nathan13888** [comment]
Hello, just came by.

@dart-coder, I've made a recreation of this using GO since I felt that this project lacked some features and since it was no longer being maintained.

My project could be found here: https://github.com/Nathan13888/VisitorBadgeReloaded

More importantly, I have plans to address this issue and to add an option to only count **unique** visitors. This option could be toggled obviously. Meanwhile, my recreation is a **direct replacement** and even keeps the exact count of what you may have currently but also has other styling features that you may be interested in.

**Comment by Nathan13888** [comment]
@miguelnietoa Please check my "fork" (not really a fork it's made from the ground up).

You have to enable this flag. However, Github made some changes to their Camo server several months ago, so just changing the caching duration doesn't work. In fact, it seems that Camo ignores this header unless it says it's expired.

So I think it's ***broken*** right now. Looks like an implementation on the server side would be required instead, which would involve caching the previous time the badge was loaded, but then that would not differentiate between different users as all requests come from Camo itself.

**Comment by miguelnietoa** [comment]
Yeah, I got it! I will look to see if there is a way to implement this feature. Thanks @Nathan13888

**Comment by Nathan13888** [comment]
Perhaps, I should make this a new Issue/Feature Request on VBR. If you have any ideas how to implement this cleanly, please let me know. If you'd like to submit a PR as well, I'd be glad to review it as well.
